# AppVeyor build configuration
# https://www.appveyor.com/docs/build-configuration
# https://www.appveyor.com/docs/appveyor-yml/
#---------------------------------#
#      general configuration      #
#---------------------------------#
# version format
version: 1.0.{build}-{branch}
image: Visual Studio 2017

# add platforms to build matrix:
platform:
  - x86

# add configurations to build matrix:
configuration:
  - Release

before_build:
  - git clone -b develop --single-branch https://github.com/meik97/XSpotify.git
#  - cmd: tree /f C:\OpenSSL-v111-Win32
  - cmd: SET PATH=C:\OpenSSL-v111-Win32;%PATH%
  - cmd: SET INCLUDE=C:\OpenSSL-v111-Win32
  - cmd: SET UseEnv=true
  - cmd: cd "XSpotify\XSpotify" 


# use custom build_script
build_script:
  - ECHO BUILD %CONFIGURATION% %PLATFORM%
  - msbuild /m XSpotify.sln /p:AdditionalIncludePaths="C:\OpenSSL-v111-Win32\include" /p:Configuration=%CONFIGURATION% /p:Platform=%PLATFORM% 
#  - msbuild /m XSpotify.sln

after_build:
  - dir
  - 7z a XSpotify.7z "C:\projects\xsp0t1fy-win32\XSpotify\XSpotify\build\lib\Release"

artifacts:  # Archive the generated packages in the ci.appveyor.com build report.  - path: bin\Debug\*
  - path: XSpotify\XSpotify\build\XSpotify.7z
    name: artifacts-all
    
